# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'lib/ui/drQt.ui'
#
# Created: Sun Oct  9 20:28:31 2011
#      by: PyQt4 UI code generator 4.8.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1144, 702)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout_4 = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.LB_header = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.LB_header.sizePolicy().hasHeightForWidth())
        self.LB_header.setSizePolicy(sizePolicy)
        self.LB_header.setMaximumSize(QtCore.QSize(16777215, 75))
        self.LB_header.setText(_fromUtf8(""))
        self.LB_header.setObjectName(_fromUtf8("LB_header"))
        self.gridLayout_4.addWidget(self.LB_header, 0, 0, 1, 1)
        self.ST_main_ = QtGui.QSplitter(self.centralwidget)
        self.ST_main_.setOrientation(QtCore.Qt.Horizontal)
        self.ST_main_.setObjectName(_fromUtf8("ST_main_"))
        self.TW_main = QtGui.QTabWidget(self.ST_main_)
        self.TW_main.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Ignored, QtGui.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TW_main.sizePolicy().hasHeightForWidth())
        self.TW_main.setSizePolicy(sizePolicy)
        self.TW_main.setObjectName(_fromUtf8("TW_main"))
        self.QW_job = QtGui.QWidget()
        self.QW_job.setObjectName(_fromUtf8("QW_job"))
        self.gridLayout = QtGui.QGridLayout(self.QW_job)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.TW_job = QtGui.QTableWidget(self.QW_job)
        self.TW_job.setAutoFillBackground(False)
        self.TW_job.setAlternatingRowColors(True)
        self.TW_job.setObjectName(_fromUtf8("TW_job"))
        self.TW_job.setColumnCount(0)
        self.TW_job.setRowCount(0)
        self.TW_job.horizontalHeader().setStretchLastSection(True)
        self.TW_job.verticalHeader().setCascadingSectionResizes(True)
        self.TW_job.verticalHeader().setStretchLastSection(False)
        self.gridLayout.addWidget(self.TW_job, 0, 0, 1, 1)
        self.TW_main.addTab(self.QW_job, _fromUtf8(""))
        self.QW_node = QtGui.QWidget()
        self.QW_node.setObjectName(_fromUtf8("QW_node"))
        self.gridLayout_2 = QtGui.QGridLayout(self.QW_node)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.TW_node = QtGui.QTableWidget(self.QW_node)
        self.TW_node.setObjectName(_fromUtf8("TW_node"))
        self.TW_node.setColumnCount(0)
        self.TW_node.setRowCount(0)
        self.TW_node.horizontalHeader().setStretchLastSection(True)
        self.TW_node.verticalHeader().setCascadingSectionResizes(True)
        self.TW_node.verticalHeader().setStretchLastSection(False)
        self.gridLayout_2.addWidget(self.TW_node, 0, 0, 1, 1)
        self.TW_main.addTab(self.QW_node, _fromUtf8(""))
        self.gridLayout_4.addWidget(self.ST_main_, 1, 0, 1, 1)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.NewJobButton = QtGui.QPushButton(self.centralwidget)
        self.NewJobButton.setObjectName(_fromUtf8("NewJobButton"))
        self.horizontalLayout_2.addWidget(self.NewJobButton)
        spacerItem = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.PB_refresh = QtGui.QPushButton(self.centralwidget)
        self.PB_refresh.setDefault(False)
        self.PB_refresh.setFlat(False)
        self.PB_refresh.setObjectName(_fromUtf8("PB_refresh"))
        self.horizontalLayout_2.addWidget(self.PB_refresh)
        spacerItem1 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.CB_auto_refresh = QtGui.QCheckBox(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.CB_auto_refresh.sizePolicy().hasHeightForWidth())
        self.CB_auto_refresh.setSizePolicy(sizePolicy)
        self.CB_auto_refresh.setObjectName(_fromUtf8("CB_auto_refresh"))
        self.horizontalLayout_2.addWidget(self.CB_auto_refresh)
        spacerItem2 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.label = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout_2.addWidget(self.label)
        self.SB_refresh_time = QtGui.QSpinBox(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SB_refresh_time.sizePolicy().hasHeightForWidth())
        self.SB_refresh_time.setSizePolicy(sizePolicy)
        self.SB_refresh_time.setObjectName(_fromUtf8("SB_refresh_time"))
        self.horizontalLayout_2.addWidget(self.SB_refresh_time)
        self.label_2 = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setMinimumSize(QtCore.QSize(81, 0))
        self.label_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_2.setAutoFillBackground(False)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout_2.addWidget(self.label_2)
        self.horizontalLayout_3.addLayout(self.horizontalLayout_2)
        self.gridLayout_4.addLayout(self.horizontalLayout_3, 2, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1144, 22))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.TW_main.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "MainWindow", None, QtGui.QApplication.UnicodeUTF8))
        self.TW_job.setSortingEnabled(True)
        self.TW_main.setTabText(self.TW_main.indexOf(self.QW_job), QtGui.QApplication.translate("MainWindow", "Jobs", None, QtGui.QApplication.UnicodeUTF8))
        self.TW_node.setSortingEnabled(True)
        self.TW_main.setTabText(self.TW_main.indexOf(self.QW_node), QtGui.QApplication.translate("MainWindow", "Slaves", None, QtGui.QApplication.UnicodeUTF8))
        self.NewJobButton.setText(QtGui.QApplication.translate("MainWindow", "New Job", None, QtGui.QApplication.UnicodeUTF8))
        self.PB_refresh.setText(QtGui.QApplication.translate("MainWindow", "Refresh", None, QtGui.QApplication.UnicodeUTF8))
        self.CB_auto_refresh.setText(QtGui.QApplication.translate("MainWindow", "Auto Refresh", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "Update every", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MainWindow", "seconds", None, QtGui.QApplication.UnicodeUTF8))

